[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
[[plugins]]
  package = "@netlify/plugin-a11y"
  [plugins.inputs]
    # Check all HTML files in this project (the default behavior)
    checkPaths = ['/']
    # Do not fail the build if a11y issues are found
    failWithIssues = false
    # Perform a11y check against WCAG 2.1 AAA
    wcagLevel = 'WCAG2AAA'
    
  package = "@netlify/plugin-lighthouse"
    # Set the plugin to run prior to deploy, failing the build if minimum thresholds aren't set 
  [plugins.inputs]
    fail_deploy_on_score_thresholds = "true"

  # Set minimum thresholds for each report area
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.7 