[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
[[plugins]]
  package = "@netlify/plugin-a11y"
  [plugins.inputs]
    checkPaths = ['/']
    failWithIssues = false
    wcagLevel = 'WCAG2AAA'
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    fail_deploy_on_score_thresholds = "true"
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.7 